on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        type: [Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - run: |
      shell: bash
    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}}
        cmake --build ${{github.workspace}}/build --config ${{matrix.type}}
        ls ${{github.workspace}}/build
        
    - name: Upload Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Release_Windows
        path: ${{github.workspace}}/build/Release/luauDec.exe

    - name: Upload Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Release_MacOS
        path: ${{github.workspace}}/build/luauDec
        
